create table t_filme(
    id number generated by default as identity,
    titulo varchar2(100),
    diretor varchar2(150),
    duracao number,
    avaliacao number(2, 1),
    sinopse varchar2(500),
    classificacao varchar2(20),
    genero varchar2(50),
    data_lancamento date,
    primary key(id)
);