import oracledb

def get_conexao():
    return oracledb.connect(user="pf0313", password="professor#23",
                            dsn="oracle.fiap.com.br/orcl")

def grava_faturamento(dados: list):
    sql = "insert into faturamento(produto, marca, loja, data, quantidade, valor) values(:produto, :marca, :loja, to_date(:data, 'DD/MM/YYYY'), :quantidade, :valor)"
    con = get_conexao()
    cur = con.cursor()

    lista_dicionarios = []
    
    for registro in dados:
        campos = registro.split(";")
        dic = {"produto": campos[0], "marca": campos[1], "loja": campos[2], "data": campos[3], "quantidade": int(campos[4]), "valor": float(campos[5])}

        lista_dicionarios.append(dic)
        #cur.execute(sql, dic)
    
    cur.executemany(sql, lista_dicionarios)
    con.commit()
    cur.close()
    con.close()

def cria_faturamento():
    sql = "create table faturamento(id number generated by default as identity, produto varchar2(50), marca varchar2(50), loja varchar2(50), data date, quantidade number(4), valor number(8, 2))"
    with get_conexao() as con:
        with con.cursor() as cur:
            cur.execute(sql)


if __name__ == "__main__":
    try:
        cria_faturamento()
    except:
        print("Faturamento já criado!")           
    
    with open('dados_venda.txt', mode="r") as arquivo:
        dados_arq = arquivo.readlines()
    
    grava_faturamento(dados_arq)

