create table tbj_midia(
    id number generated by default as identity primary key,
    titulo varchar2(100),
    categoria varchar2(40),
    avaliacao number(2, 1),
    qtd_avaliacoes number(4),
    tipo char
);

create table tbj_usuario(
    id number generated by default as identity primary key,
    nome varchar2(100),
    email varchar2(100),
    senha varchar2(255)
);

create table tbj_preferencias(
    id number generated by default as identity primary key,
    datahora timestamp,
    id_midia number,
    id_usuario number,
    foreign key(id_midia) references tbj_midia(id),
    foreign key(id_usuario) references tbj_usuario(id)
);





