create table t_time(
    id number generated by default as identity,
    nome varchar2(50),
    vitorias number,
    empates number,
    derrotas number,
    gols_contra number,
    gols_pro number,
    primary key(id)
);

create table t_partida(
    id number generated by default as identity,
    gols_casa number,
    gols_visi number,
    rodada number,
    id_casa number,
    id_visi number,
    foreign key (id_casa) references t_time(id),
    foreign key (id_visi) references t_time(id),
    primary key(id)
);